site_name: Watson AIOps
site_url: https://jorgego11.github.io/aiopslabs/
nav:
    - Configuring Data Sources: integration.md
    - Log Anomaly Training: log-anomaly.md
    - Log Anomaly Inference: inference.md
    - About: about.md
theme: readthedocs

